// react/react04/redux-demo/src/redux_基本使用 copy/Num1.js
import React ,{Component} from 'react'
import Store from './store'
import ActionCreator from './actionCreator'
class Num1 extends Component{
  componentDidMount(){
    Store.subscribe(()=>{
      // 全局状态值发生改变
      this.setState({})
    })
  }
  render(){
    console.log(Store)
    console.log(Store.getState())
    let {num,name}=Store.getState()
    return(
      <div>
        <h1>num1</h1>
        {num}
        {name}
        <button onClick={()=>{
          ActionCreator.addnum()
          // 触发action下的方法
        }}>add</button>
      </div>
    )
  }
}
export default Num1

// vue/music/src/demo/vuexdemo/num1.vue
<template>
  <div>
   这是组件1
   {{this.$store.state.num}}
   {{this.$store.state.name}}
     {{this.$store.getters.double}}
   <button @click='add'>add</button>
  </div>
</template>
<script>
export default {
  methods: {
    add(){
      // this.$store.commit('addNum',5)
      this.$store.dispatch('actionNum',5)
    }
  },
  mounted() {
    console.log('num1',this.$store)
  },
}
</script>
<style lang="less" scoped>

</style>
