// react/react04/redux-demo/src/redux/Num2.js
import React ,{Component} from 'react'
import Store from './store'
import ActionCreator from './actionCreator'
class Num2 extends Component{
  componentDidMount(){
    Store.subscribe(()=>{
      this.setState({})
    })
  }
  render(){
    let {num,name}=Store.getState()
    return(
      <div>
        <h1>num2</h1>
        {num}
        {name}
       <button onClick={()=>{
         ActionCreator.changeName('韩梅梅')
       }}>改名</button>
      </div>
    )
  }
}
export default Num2

// vue/music/src/demo/vuexdemo/num2.vue
<template>
  <div>
   这是组件2
   {{this.$store.state.num}}
   {{this.$store.state.name}}
    {{this.$store.getters.double}}
   <button @click='changename'>改名</button> 
  </div>
</template>
<script>
export default {
  methods: {
    changename(){
      this.$store.commit('changeName','李雷')
    }
  },
 mounted() {
    console.log('num2',this.$store)
  },
}
</script>
<style lang="less" scoped>

</style>
