// vue/music/src/demo/vuexdemo/num1.vue
<template>
  <div>
   这是组件1
   {{this.$store.state.num}}
   {{this.$store.state.name}}
     {{this.$store.getters.double}}
   <button @click='add'>add</button>
  </div>
</template>
<script>
export default {
  methods: {
    add(){
      // this.$store.commit('addNum',5)
      this.$store.dispatch('actionNum',5)
    }
  },
  mounted() {
    console.log('num1',this.$store)
  },
}
</script>
<style lang="less" scoped>

</style>

// react/react04/redux-demo/src/redux_上下文优化/Num1.js
import React ,{Component} from 'react'
import connect from '../context/connect'
import ActionCreator from './actionCreator'
class Num1 extends Component{

  render(){
    console.log(this,'num1')
    return(
      <div>
        <h1>num1</h1>
        {this.props.store.num}
        <hr/>
        {this.props.store.name}
        <button onClick={()=>{
          ActionCreator.addnum()
          // 触发action下的方法
        }}>add</button>
      </div>
    )
  }
}

export default connect(Num1)
