// vue/music/src/demo/vuexdemo/num1.vue
<template>
  <div>
   这是组件1
   {{this.$store.state.num}}
   {{this.$store.state.name}}
     {{this.$store.getters.double}}
   <button @click='add'>add</button>
  </div>
</template>
<script>
export default {
  methods: {
    add(){
      // this.$store.commit('addNum',5)
      this.$store.dispatch('actionNum',5)
    }
  },
  mounted() {
    console.log('num1',this.$store)
  },
}
</script>
<style lang="less" scoped>

</style>

// react/react04/redux-demo/src/redux/Num1.js
import React ,{Component} from 'react'
import Store from './store'
class Num1 extends Component{
  render(){
    console.log(Store)
    console.log(Store.getState())
    let {num,name}=Store.getState()
    return(
      <div>
        <h1>num1</h1>
        {num}
        {name}
      </div>
    )
  }
}
export default Num1
